CREATE TABLE RESIDENT (
	RESID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	FIRSTNAME VARCHAR(100) NOT NULL, 
	SURENAME VARCHAR(100) NOT NULL, 
	DOB DATE, 
	ADDRESS VARCHAR(256) NOT NULL, 
	POSTCODE DECIMAL(16), 
	EMAIL VARCHAR(256), 
	MOBILE VARCHAR(17) NOT NULL, 
	NOOFRESIDENTS INTEGER NOT NULL, 
	ENERGYPROVIDER VARCHAR(100), 
	PRIMARY KEY (RESID)
);

Alter Table resident Add Constraint constraint1 Check(email like '%_@_%');
Alter Table resident Add Constraint constraint2 Check(noofresidents>=1);
