CREATE TABLE CREDENTIAL (
	USERNAME VARCHAR(64) NOT NULL PRIMARY KEY,
	RESID INTEGER NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	REGISTRATIONDATE DATE NOT NULL
);

Alter Table credential Add Foreign Key (resid) References resident (resid);